# Generated by Django 2.2.5 on 2020-04-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeidl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-pk']},
        ),
    ]
