# Generated by Django 2.2.5 on 2019-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeidl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identificacion',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
