# Generated by Django 2.2.5 on 2019-10-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeidl', '0002_auto_20190924_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
