# Generated by Django 2.2.5 on 2019-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeidl', '0003_medic_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
