# Generated by Django 2.2.5 on 2020-04-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeidl', '0003_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='medic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppAeidl.Medic'),
        ),
    ]
