# Generated by Django 2.2.5 on 2019-10-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeidl', '0004_auto_20191002_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medic',
            name='email',
        ),
    ]
