# Generated by Django 2.2.5 on 2020-04-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeidl', '0004_auto_20200426_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='result',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
