# Generated by Django 2.2.5 on 2019-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeidl', '0005_remove_medic_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
